# Generated by Django 4.2.16 on 2025-11-12 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lordsonApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
