# Generated by Django 4.2.16 on 2025-11-12 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lordsonApp', '0004_product_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
